# Generated by Django 3.1.5 on 2021-01-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_crud_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='model',
            field=models.CharField(default='Product without model', max_length=100),
        ),
    ]
