# Generated by Django 3.1.5 on 2021-01-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_crud_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=200, verbose_name='тест комментария')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.crud')),
            ],
        ),
    ]
