# Generated by Django 3.1.5 on 2021-02-07 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField(default='')),
                ('count', models.PositiveIntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 2, 7, 14, 22, 55, 367793))),
            ],
        ),
        migrations.CreateModel(
            name='Crud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Product without title', max_length=100)),
                ('model', models.CharField(default='Product without model', max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('discription', models.TextField(default='')),
                ('quantity', models.IntegerField(default=0)),
                ('activation', models.BooleanField(default=False)),
                ('image', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.cart')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.crud')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=200, verbose_name='тест комментария')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.crud')),
            ],
        ),
    ]
