# Generated by Django 3.1.5 on 2021-02-08 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_remove_crud_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 20, 3, 59, 585058)),
        ),
    ]
