# Generated by Django 3.1.5 on 2021-01-25 18:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 25, 18, 41, 38, 416227, tzinfo=utc)),
        ),
    ]
